name: qtiplot-wrap
description: Snap wrap for qtiplot
summary: Wrapper
grade: stable
license: GPL-2.0
version: 1.0.0
base: core18
confinement: strict

apps:
  qtiplot-wrap:
    command: usr/bin/qtiplot
    extensions: [gnome-3-28]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: com.marvinav.qtiplot-wrap

parts:
  qtiplot-wrap:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/universe/q/qtiplot/qtiplot_0.9.8.9-17_amd64.deb
    stage-packages:
      - libalglib3.11
      - libgcc1
      - libgl1
      - libgl1-mesa-glx
      - libgl2ps1.4
      - libglu1
      - libglu1-mesa
      - libgsl23
      - libgslcblas0
      - libmuparser2v5
      - libpython2.7
      - libqt4-network
      - libqt4-opengl
      - libqt4-qt3support
      - libqt4-svg
      - libqt4-xml
      - libqtassistantclient4
      - libqtcore4
      - libqtexengine1
      - libqtgui4
      - libstdc++6
      - libtamuanova-0.2
      - python
      - zlib1g
      - sip-api-12.3


slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.marvinav.qtiplot-wrap
